apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    service: project
spec:
  replicas: 1
  selector:
    matchLabels:
      service: project
  template:
    metadata:
      labels:
        service: project
    spec:
      containers:
      - name: project-container
        image: hhana982/project:1.<version>
        ports:
        - containerPort: 5000
        env: 
        - name: num
          value: "5"