apiVersion: v1
kind: Service
metadata:
  name: project
  labels:
    service: project
spec:
  selector:
    app: project
    service: project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP