apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-mysql-deployment
  labels:
    app: mysql
    service: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      service: project
  template:
    metadata:
      labels:
        app: mysql
        service: project
    spec:
      containers:
      - name: project-mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootpassword'
