apiVersion: v1
kind: Service
metadata:
  name: project-mysql
  labels:
    app: mysql
    service: project
spec:
  selector:
    app: mysql
    service: project
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP